spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:56161/railway
spring.datasource.username=root
spring.datasource.password=qfWJTrdLpDLJMjdHKiNtYHMuqlpHghtI
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
server.port=8080

